name: tests

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Docker Compose
        run: docker-compose up -d
      - name: Install Wait For It Ubuntu package
        run: sudo apt-get install wait-for-it
      - name: Wait until PostgreSQL is ready
        run: wait-for-it 127.0.0.1:15432 --timeout=20
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          set -ex
          curl -sSL https://install.python-poetry.org | python3 -
          $HOME/.local/bin/poetry install
      - name: Copy env.example to .env
        run: |
          set -ex
          test -f env.example && cp -a env.example .env || echo "env.example doesn't exist. It's OK"
      - name: Test with pytest
        run: |
          set -ex
          $HOME/.local/bin/poetry run coverage run -m pytest
      - name: Convert coverage to XML
        run: |
          set -ex
          $HOME/.local/bin/poetry run coverage xml
      - name: Upload coverage to codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          bash <(curl -s https://codecov.io/bash)
